### ISSUE TITLE
Class 'SocialFeed' not found in /XXX/cron.php on line

### ISSUE THREAD

**Issue by drewdeakin** [codeurs/social-feed#1]
Getting the error when I run the file;

Class 'SocialFeed' not found in /XXX/cron.php on line

Here's the code that I am using

```
<?php

 require_once( 'src/SocialFeed.php' );

 $feed = new SocialFeed();

 // Input api credentials
 $feed->facebook->setCredentials([
  'app_id' => 'XXX',
  'app_secret' => 'XXX'
 ]);

?>
```

**Comment by benmerckx** [comment]
You'll want to import the class from the namespace after the require with:
`use Codeurs\SocialFeed\SocialFeed;`
or instead creating a new instance with:
`$feed = new Codeurs\SocialFeed\SocialFeed();`
